name: Publish

on:
  push:
    branches:
      - '*'

jobs:
  publish_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set Env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Inspect Builder
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: nikitanovosibirsk
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: nikitanovosibirsk/test:latest
