name: Test

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set Env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Test Env
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
